// 5_React/7-router/src/pages/Home.js
// import { useGetQuery } from "../api/animal";
import { getAnimals, delAnimal } from "../api/animal";
import { useEffect, useState } from "react";
import styled from "styled-components";

const Table = styled.table`
    width: 100%;
    th{
        font-weight: bold;
        padding:  10px;
    }
    td{
        padding: 10px;
        text-align: center;
        border-top: 1px dashed gray;
    }
`;

const Home = ()=>{
    // const {data} = useGetQuery();
    const [animals, setAnimals] = useState([]);

    const animalAPI = async ()=>{
        const result = await getAnimals();
        console.log(result.data);
        setAnimals(result.data);
        
    };

    useEffect(()=>{
        animalAPI();
    },[]);

    // 삭제
    const onDelete = async(no)=>{
       await delAnimal(no);
       setAnimals(animals.filter((animal)=>animal.no !== no))
    }


    return (
    <Table>
        <thead>
            <tr>
                <th>이름</th>
                <th>나이</th>
                <th>삭제</th>
            </tr>
        </thead>
        <tbody>
            {animals.map((animal)=>(
            <tr key={animal.no}>
                <td>{animal.name}</td>
                <td>{animal.age}</td>
                <td><button onClick={()=>onDelete(animal.no)}>삭제</button></td>
            </tr>
            ))}
            
        </tbody>
    </Table>
    );
};
export default Home;

// movie-vue/src/pages/Home.vue
<template>
  <h1>영화 목록</h1>
  <table>
    <thead>
      <tr>
        <th>제목</th>
        <th>장르</th>
        <th>영화배우</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="movie in movies" :key="movie.no">
        <td>{{ movie.title }}</td>
        <td>{{ movie.genre }}</td>
        <td>{{ movie.actor }}</td>
        <td><button @click="delete1(movie.no)">삭제</button></td>
      </tr>
    </tbody>
  </table>
</template>
<script>
// import { getMovies, deleteMovie } from "@/api/movie";
// delete는 예약어 쓸수없음
export default {
  name: "HomePage",
  computed: {
    movies() {
      return this.$store.state.movie.movies;
    },
  },
  // data() {
  //   return {
  //     movies: [],
  //   };
  // },
  created() {
    // this.fetchMovies();
    this.$store.dispatch("fetchMovies");
  },
  methods: {
    // async fetchMovies() {
    //   const response = await getMovies();
    //   this.movies = response.data;
    // },
    async delete1(no) {
      this.$store.dispatch("delMovie", no);

      // await deleteMovie(no);
      // await this.fetchMovies();
    },
  },
};
</script>
<style>
h1 {
  font-size: 2.5rem;
  font-weight: bold;
  margin-top: 30px;
  margin-bottom: 30px;
  text-align: center;
}
table {
  width: 900px;
  margin: auto;
  text-align: center;
  th {
    width: 25%;
    font-weight: bold;
  }
  td {
    padding-top: 20px;
  }
}
</style>
